package org.jogre.gameOfThrones.common.territory;

import java.util.HashMap;// UTILISER UNE TABLE HACHAGE OU LISTE ???
import java.util.Map;

import sun.awt.windows.ThemeReader;


public class BoardModel {

	public Map<String,Territory> board;//rendre privé
	//public static BoardModel BAORD = new BoardModel();// Inutile maintenant
	
	public BoardModel(){
		board = new HashMap<String,Territory>();
		
		//Territory creation
		Territory Winterfell = new HomeLand("Winterfell",1,1);
		Territory CastleBlack = new Land("Castle Black",1,0,0);
		Territory Karhold = new Land("Karhold",1,0,0);
		Territory StonyShore = new Land("The Stony Shore",0,1,0);
		Territory WhiteHarbor = new Land("White Harbor",0,0,1);
		Territory WidowWatch = new Land("Widow's Watch",0,1,0);
		Territory BayOfIce = new Water("Bay Of Ice");
		Territory ShiveringSea = new Water("Shivering Sea");
		Territory NarrowSea = new Water("Narrow Sea");
		Territory IronmanBay = new Water("Ironman's Bay");
		Territory moatCailin = new Land("Moat Cailin",0,0,1);
		Territory GreyWaterWatch = new Land("GreyWater Watch",0,1,0);
		Territory FlintFinger = new Land("Flint's Finger",0,0,1);
		Territory sunsetSea = new Water("Sunset Sea");
		Territory Pike = new HomeLand("Pike",1,1);
		Territory Seaguard = new Land("Seaguard",1,1,2);
		Territory Riverrun = new Land("Riverrun",1,1,2);
		Territory Twins = new Land("The Twins",1,0,0);
		Territory Fingers = new Land("The Fingers",0,1,0);
		Territory MountainsMoon = new Land("The Moutains of the Moon",1,0,0);
		Territory Eyrie = new Land("The Eyrie",1,1,1);
		Territory Lannisport = new HomeLand("Lannisport",0,2);
		Territory GoldenSound = new Water("The Golden Sound");
		Territory Dragonstone = new HomeLand("Dragonstone",1,1);
		Territory Harrenhal = new Land("Harrenhal",1,0,1);
		Territory StoneySept= new Land("Stoney Sept",1,0,0);
		Territory CrackclawPoint= new Land("Crackclaw Point",0,0,1);
		Territory SearoadMarches= new Land("Searoad Marches",0,1,0);
		Territory Blackwater= new Land("Blackwater",0,2,0);
		Territory BlackwaterBay= new Water("Blackwater Bay");
		Territory Shipbreaker= new Water("Shipbreaker Bay");
		Territory Kingswood= new Land("Kingswood",1,1,0);
		Territory Reach= new Land("The Reach",0,0,1);
		Territory StormsEnd= new Land("Storm's End",0,0,1);
		Territory Highgarden= new HomeLand("Highgarden",0,2);
		Territory Sunspear= new HomeLand("Sunspear",1,1);
		Territory KingsLanding= new Land("King's Landing",2,0,2);
		Territory Oldtown= new Land("Oldtown",0,0,2);
		Territory DornishMarches= new Land("Dornish Marches",1,0,0);
		Territory Boneway= new Land("The Boneway",1,0,0);
		Territory Arbor= new Land("The Arbor",1,0,0);
		Territory RedwyneStraights= new Water("Redwyne Straights");
		Territory SeaOfDorne= new Water("Sea of Dorne");
		Territory ThreeTowers= new Land("Three Towers",0,1,0);
		Territory PrincePass= new Land("Prince's Pass",1,1,0);
		Territory Starfall= new Land("Starfall",0,1,1);
		Territory Yronwood= new Land("Yronwood",0,0,1);
		Territory SaltShore= new Land("Salt Shore",0,1,0);
		Territory WestSummerSea= new Water("West Summer Sea");
		Territory EastSummerSea= new Water("East Summer Sea");
		//ports
		Territory winterfellPort= new Port("Winterfell's Port");
		Territory whiteHarborPort= new Port("White Harbor's Port");
		Territory pikePort= new Port("Pike's Port");
		Territory dragonstonePort= new Port("Dragonstone's Port");
		
		Territory lannisportPort= new Port("Lannisport's Port");
		Territory sunspearPort= new Port("Sunspear's Port");
		Territory stormEndPort= new Port("Storm's End's Port");
		Territory oldtownPort= new Port("Oldtown's Port");
		
		//here we add neighborhoods
		//(tout faire en double, ex : Karhold.addTerritory(Winterfell); Winterfell.addTerritory(Karhold); )
		EastSummerSea.addTerritory(WestSummerSea);
		EastSummerSea.addTerritory(Starfall);
		EastSummerSea.addTerritory(SaltShore);
		EastSummerSea.addTerritory(Sunspear);
		EastSummerSea.addTerritory(SeaOfDorne);
		EastSummerSea.addTerritory(StormsEnd);
		EastSummerSea.addTerritory(Shipbreaker);
		WestSummerSea.addTerritory(EastSummerSea);
		WestSummerSea.addTerritory(Starfall);
		WestSummerSea.addTerritory(Arbor);
		WestSummerSea.addTerritory(RedwyneStraights);
		WestSummerSea.addTerritory(ThreeTowers);
		WestSummerSea.addTerritory(Highgarden);
		WestSummerSea.addTerritory(SearoadMarches);
		WestSummerSea.addTerritory(sunsetSea);
		SaltShore.addTerritory(EastSummerSea);
		SaltShore.addTerritory(Yronwood);
		SaltShore.addTerritory(Sunspear);
		SaltShore.addTerritory(Starfall);
		Yronwood.addTerritory(SeaOfDorne);
		Yronwood.addTerritory(Boneway);
		Yronwood.addTerritory(Starfall);
		Yronwood.addTerritory(PrincePass);
		Yronwood.addTerritory(SaltShore);
		Yronwood.addTerritory(Sunspear);
		Starfall.addTerritory(PrincePass);
		Starfall.addTerritory(Yronwood);
		Starfall.addTerritory(SaltShore);
		Starfall.addTerritory(WestSummerSea);
		Starfall.addTerritory(EastSummerSea);
		PrincePass.addTerritory(ThreeTowers);
		PrincePass.addTerritory(DornishMarches);
		PrincePass.addTerritory(Boneway);
		PrincePass.addTerritory(Yronwood);
		PrincePass.addTerritory(Starfall);
		ThreeTowers.addTerritory(WestSummerSea);
		ThreeTowers.addTerritory(RedwyneStraights);
		ThreeTowers.addTerritory(PrincePass);
		ThreeTowers.addTerritory(DornishMarches);
		ThreeTowers.addTerritory(Oldtown);
		SeaOfDorne.addTerritory(EastSummerSea);
		SeaOfDorne.addTerritory(Sunspear);
		SeaOfDorne.addTerritory(StormsEnd);
		SeaOfDorne.addTerritory(Boneway);
		SeaOfDorne.addTerritory(Yronwood);
		RedwyneStraights.addTerritory(Arbor);
		RedwyneStraights.addTerritory(WestSummerSea);
		RedwyneStraights.addTerritory(Highgarden);
		RedwyneStraights.addTerritory(Oldtown);
		RedwyneStraights.addTerritory(ThreeTowers);
		Arbor.addTerritory(RedwyneStraights);
		Arbor.addTerritory(WestSummerSea);
		Boneway.addTerritory(Reach);
		Boneway.addTerritory(DornishMarches);
		Boneway.addTerritory(PrincePass);
		Boneway.addTerritory(Yronwood);
		Boneway.addTerritory(SeaOfDorne);
		Boneway.addTerritory(Kingswood);
		Boneway.addTerritory(StormsEnd);
		DornishMarches.addTerritory(Highgarden);
		DornishMarches.addTerritory(Reach);
		DornishMarches.addTerritory(Boneway);
		DornishMarches.addTerritory(ThreeTowers);
		DornishMarches.addTerritory(PrincePass);
		DornishMarches.addTerritory(Oldtown);
		Oldtown.addTerritory(DornishMarches);
		Oldtown.addTerritory(RedwyneStraights);
		Oldtown.addTerritory(ThreeTowers);
		Oldtown.addTerritory(Highgarden);
		KingsLanding.addTerritory(CrackclawPoint);
		KingsLanding.addTerritory(BlackwaterBay);
		KingsLanding.addTerritory(Blackwater);
		KingsLanding.addTerritory(Reach);
		KingsLanding.addTerritory(Kingswood);
		Sunspear.addTerritory(SaltShore);
		Sunspear.addTerritory(Yronwood);
		Sunspear.addTerritory(EastSummerSea);
		Sunspear.addTerritory(SeaOfDorne);
		Highgarden.addTerritory(Oldtown);
		Highgarden.addTerritory(SearoadMarches);
		Highgarden.addTerritory(Reach);
		Highgarden.addTerritory(DornishMarches);
		Highgarden.addTerritory(RedwyneStraights);
		Highgarden.addTerritory(WestSummerSea);
		StormsEnd.addTerritory(Boneway);
		StormsEnd.addTerritory(Kingswood);
		StormsEnd.addTerritory(Shipbreaker);
		StormsEnd.addTerritory(SeaOfDorne);
		StormsEnd.addTerritory(EastSummerSea);
		Reach.addTerritory(SearoadMarches);
		Reach.addTerritory(Blackwater);
		Reach.addTerritory(Highgarden);
		Reach.addTerritory(KingsLanding);
		Reach.addTerritory(Kingswood);
		Reach.addTerritory(Boneway);
		Reach.addTerritory(DornishMarches);
		Kingswood.addTerritory(KingsLanding);
		Kingswood.addTerritory(Boneway);
		Kingswood.addTerritory(StormsEnd);
		Kingswood.addTerritory(Reach);
		Kingswood.addTerritory(Shipbreaker);
		Kingswood.addTerritory(BlackwaterBay);
		Shipbreaker.addTerritory(BlackwaterBay);
		Shipbreaker.addTerritory(Dragonstone);
		Shipbreaker.addTerritory(CrackclawPoint);
		Shipbreaker.addTerritory(Kingswood);
		Shipbreaker.addTerritory(StormsEnd);
		Shipbreaker.addTerritory(EastSummerSea);
		Shipbreaker.addTerritory(NarrowSea);
		BlackwaterBay.addTerritory(KingsLanding);
		BlackwaterBay.addTerritory(CrackclawPoint);
		BlackwaterBay.addTerritory(Kingswood);
		BlackwaterBay.addTerritory(Shipbreaker);
		Blackwater.addTerritory(Harrenhal);
		Blackwater.addTerritory(CrackclawPoint);
		Blackwater.addTerritory(KingsLanding);
		Blackwater.addTerritory(Reach);
		Blackwater.addTerritory(StoneySept);
		Blackwater.addTerritory(SearoadMarches);
		CrackclawPoint.addTerritory(Harrenhal);
		CrackclawPoint.addTerritory(KingsLanding);
		CrackclawPoint.addTerritory(Blackwater);
		CrackclawPoint.addTerritory(MountainsMoon);
		CrackclawPoint.addTerritory(BlackwaterBay);
		CrackclawPoint.addTerritory(Shipbreaker);
		CrackclawPoint.addTerritory(NarrowSea);
		StoneySept.addTerritory(Lannisport);
		StoneySept.addTerritory(Riverrun);
		StoneySept.addTerritory(Harrenhal);
		StoneySept.addTerritory(Blackwater);
		StoneySept.addTerritory(SearoadMarches);
		SearoadMarches.addTerritory(Lannisport);
		SearoadMarches.addTerritory(StoneySept);
		SearoadMarches.addTerritory(Blackwater);
		SearoadMarches.addTerritory(Reach);
		SearoadMarches.addTerritory(Highgarden);
		SearoadMarches.addTerritory(GoldenSound);
		SearoadMarches.addTerritory(sunsetSea);
		SearoadMarches.addTerritory(WestSummerSea);
		Harrenhal.addTerritory(Riverrun);
		Harrenhal.addTerritory(StoneySept);
		Harrenhal.addTerritory(Blackwater);
		Harrenhal.addTerritory(CrackclawPoint);
		Dragonstone.addTerritory(Shipbreaker);
		GoldenSound.addTerritory(Riverrun);
		GoldenSound.addTerritory(Lannisport);
		GoldenSound.addTerritory(SearoadMarches);
		GoldenSound.addTerritory(IronmanBay);
		GoldenSound.addTerritory(sunsetSea);
		Lannisport.addTerritory(GoldenSound);
		Lannisport.addTerritory(SearoadMarches);
		Lannisport.addTerritory(StoneySept);
		Lannisport.addTerritory(Riverrun);
		Eyrie.addTerritory(MountainsMoon);
		Eyrie.addTerritory(NarrowSea);
		Fingers.addTerritory(Twins);
		Fingers.addTerritory(MountainsMoon);
		Fingers.addTerritory(NarrowSea);
		MountainsMoon.addTerritory(Fingers);
		MountainsMoon.addTerritory(Twins);
		MountainsMoon.addTerritory(CrackclawPoint);
		MountainsMoon.addTerritory(Eyrie);
		MountainsMoon.addTerritory(NarrowSea);
		Twins.addTerritory(Fingers);
		Twins.addTerritory(moatCailin);
		Twins.addTerritory(Seaguard);
		Twins.addTerritory(MountainsMoon);
		Twins.addTerritory(NarrowSea);
		Pike.addTerritory(IronmanBay);
		Seaguard.addTerritory(Riverrun);
		Seaguard.addTerritory(GreyWaterWatch);
		Seaguard.addTerritory(moatCailin);
		Seaguard.addTerritory(Twins);
		Seaguard.addTerritory(IronmanBay);
		Riverrun.addTerritory(Seaguard);
		Riverrun.addTerritory(IronmanBay);
		Riverrun.addTerritory(GoldenSound);
		Riverrun.addTerritory(Lannisport);
		Riverrun.addTerritory(StoneySept);
		Riverrun.addTerritory(Harrenhal);
		IronmanBay.addTerritory(Pike);
		IronmanBay.addTerritory(sunsetSea);
		IronmanBay.addTerritory(FlintFinger);
		IronmanBay.addTerritory(GoldenSound);
		IronmanBay.addTerritory(GreyWaterWatch);
		IronmanBay.addTerritory(Seaguard);
		IronmanBay.addTerritory(Riverrun);
		sunsetSea.addTerritory(FlintFinger);
		sunsetSea.addTerritory(BayOfIce);
		sunsetSea.addTerritory(IronmanBay);
		sunsetSea.addTerritory(GoldenSound);
		sunsetSea.addTerritory(SearoadMarches);
		FlintFinger.addTerritory(GreyWaterWatch);
		FlintFinger.addTerritory(sunsetSea);
		FlintFinger.addTerritory(IronmanBay);
		FlintFinger.addTerritory(BayOfIce);
		GreyWaterWatch.addTerritory(moatCailin);
		GreyWaterWatch.addTerritory(FlintFinger);
		GreyWaterWatch.addTerritory(IronmanBay);
		GreyWaterWatch.addTerritory(BayOfIce);
		moatCailin.addTerritory(WhiteHarbor);
		moatCailin.addTerritory(Winterfell);
		moatCailin.addTerritory(GreyWaterWatch);
		moatCailin.addTerritory(NarrowSea);
		ShiveringSea.addTerritory(Karhold);
		ShiveringSea.addTerritory(CastleBlack);
		ShiveringSea.addTerritory(Winterfell);
		ShiveringSea.addTerritory(WhiteHarbor);
		ShiveringSea.addTerritory(WidowWatch);
		ShiveringSea.addTerritory(NarrowSea);
		CastleBlack.addTerritory(Winterfell);
		CastleBlack.addTerritory(Karhold);
		CastleBlack.addTerritory(BayOfIce);
		CastleBlack.addTerritory(ShiveringSea);
		Karhold.addTerritory(ShiveringSea);
		Karhold.addTerritory(CastleBlack);
		Karhold.addTerritory(Winterfell);
		Winterfell.addTerritory(Karhold);
		Winterfell.addTerritory(CastleBlack);
		Winterfell.addTerritory(StonyShore);
		Winterfell.addTerritory(ShiveringSea);
		Winterfell.addTerritory(BayOfIce);
		Winterfell.addTerritory(WhiteHarbor);
		Winterfell.addTerritory(moatCailin);
		NarrowSea.addTerritory(CrackclawPoint);
		NarrowSea.addTerritory(Shipbreaker);
		NarrowSea.addTerritory(Eyrie);
		NarrowSea.addTerritory(MountainsMoon);
		NarrowSea.addTerritory(Twins);
		NarrowSea.addTerritory(Fingers);
		NarrowSea.addTerritory(WhiteHarbor);
		NarrowSea.addTerritory(WidowWatch);
		NarrowSea.addTerritory(ShiveringSea);
		NarrowSea.addTerritory(moatCailin);
		BayOfIce.addTerritory(CastleBlack);
		BayOfIce.addTerritory(Winterfell);
		BayOfIce.addTerritory(StonyShore);
		BayOfIce.addTerritory(GreyWaterWatch);
		BayOfIce.addTerritory(sunsetSea);
		BayOfIce.addTerritory(FlintFinger);
		StonyShore.addTerritory(Winterfell);
		StonyShore.addTerritory(BayOfIce);
		WhiteHarbor.addTerritory(Winterfell);
		WhiteHarbor.addTerritory(WidowWatch);
		WhiteHarbor.addTerritory(ShiveringSea);
		WhiteHarbor.addTerritory(NarrowSea);
		WhiteHarbor.addTerritory(moatCailin);
		WidowWatch.addTerritory(WhiteHarbor);
		WidowWatch.addTerritory(NarrowSea);
		WidowWatch.addTerritory(ShiveringSea);
		//ports
		winterfellPort.addTerritory(Winterfell);
		winterfellPort.addTerritory(BayOfIce);
		whiteHarborPort.addTerritory(WhiteHarbor);
		whiteHarborPort.addTerritory(NarrowSea);
		pikePort.addTerritory(Pike);
		pikePort.addTerritory(IronmanBay);
		dragonstonePort.addTerritory(Dragonstone);
		dragonstonePort.addTerritory(Shipbreaker);
		lannisportPort.addTerritory(Lannisport);
		lannisportPort.addTerritory(GoldenSound);
		stormEndPort.addTerritory(StormsEnd);
		stormEndPort.addTerritory(Shipbreaker);
		sunspearPort.addTerritory(Sunspear);
		sunspearPort.addTerritory(EastSummerSea);
		oldtownPort.addTerritory(Oldtown);
		oldtownPort.addTerritory(RedwyneStraights);
		
		
		
		
		// the territory are had to the map
		board.put("Winterfell", Winterfell);
		board.put("Castle Black", CastleBlack);
		board.put("Karhold", Karhold);
		board.put("Shivering Sea", ShiveringSea);
		board.put("Narrow Sea", NarrowSea);
		board.put("Bay Of Ice", BayOfIce);
		board.put("The Stony Shore", StonyShore);
		board.put("White Harbor", WhiteHarbor);
		board.put("Widow's Watch", WidowWatch);
		board.put("Moat Cailin", moatCailin);
		board.put("GreyWater Watch", GreyWaterWatch);
		board.put("Flint's Finger", FlintFinger);
		board.put("Sunset Sea", sunsetSea);
		board.put("Ironman's Bay", IronmanBay);
		board.put("The Golden Sound", GoldenSound);
		board.put("Pike", Pike);
		board.put("Seaguard", Seaguard);
		board.put("Riverrun", Riverrun);
		board.put("The Twins", Twins);
		board.put("The Fingers", Fingers);
		board.put("The Mountains of the Moon", MountainsMoon);
		board.put("The Eyrie", Eyrie);
		board.put("Lannisport", Lannisport);
		board.put("Dragonstone", Dragonstone);
		board.put("Harrenhal", Harrenhal);
		board.put("Stoney Sept", StoneySept);
		board.put("Crackclaw Point", CrackclawPoint);
		board.put("Searoad Marches", SearoadMarches);
		board.put("Blackwater", Blackwater);
		board.put("Blackwater Bay", BlackwaterBay);
		board.put("Shipbreaker Bay", Shipbreaker);
		board.put("Kingswood", Kingswood);
		board.put("The Reach", Reach);
		board.put("Storm's End", StormsEnd);
		board.put("Highgarden", Highgarden);
		board.put("Sunspear", Sunspear);
		board.put("King's Landing", KingsLanding);
		board.put("Oldtown", Oldtown);
		board.put("Dornish Marches", DornishMarches);
		board.put("The Boneway", Boneway);
		board.put("The Arbor", Arbor);
		board.put("Redwyne Straights", RedwyneStraights);
		board.put("Sea of Dorne", SeaOfDorne);
		board.put("Three Towers", ThreeTowers);
		board.put("Prince's Pass", PrincePass);
		board.put("Starfall", Starfall);
		board.put("Yronwood", Yronwood);
		board.put("Three Towers", ThreeTowers);
		board.put("Salt Shore", SaltShore);
		board.put("East Summer Sea", EastSummerSea);
		board.put("West Summer Sea", WestSummerSea);
		board.put("Winterfell's Port", winterfellPort);
		board.put("White Harbor's Port", whiteHarborPort);
		board.put("Pike's Port", pikePort);
		board.put("Dragonstone's Port", dragonstonePort);
		board.put("Storm's End's Port", StormsEnd);
		board.put("Oldtown's Port", oldtownPort);
		board.put("Lannisport's Port", lannisportPort);
		board.put("Sunspear's Port", sunspearPort);
		
		
	}


	public Territory getTerritory(String name){
		return board.get(name);
	}
}
